[package]
name = "figures"
version = "0.1.0"
authors = ["iker"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
clap = "~2.33"
rand = "0.7"
time = "*"
